apiVersion: v1
kind: Service
metadata:
  name: demo-backend
  namespace: demo-app
spec:
  selector:
    app: demo-backend
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
