apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: demo-frontend-http
  namespace: demo-app
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`demo.klassify.com`)
      services:
        - name: demo-frontend
          port: 80
